### ISSUE TITLE
SELECT * FROM <cross join> output isn't nested by table name

### ISSUE THREAD

**Issue by rychipman** [partiql/partiql-lang-kotlin#275]
Based on my reading of section 5.3 of the spec, the top-level keys in the output of a FROM clause with a cross join are the names of the tables being joined. However, when I `SELECT *` from such a join, the results don't seem to be namespaced in that way:
```
PartiQL> select * from [{'a':1},{'a':2}] foo cross join [{'b':1},{'b':2}] bar
   | 
===' 
<<
  {
    'a': 1,
    'b': 1
  },
  {
    'a': 1,
    'b': 2
  },
  {
    'a': 2,
    'b': 1
  },
  {
    'a': 2,
    'b': 2
  }
>>
```

The fact that I _can_ access the fields by table name suggests that it might be `SELECT *`, not the `JOIN`, that is eliding the table names, as shown in the following query:
```
PartiQL> select foo, bar from [{'a':1},{'a':2}] foo cross join [{'b':1},{'b':2}] bar
   | 
===' 
<<
  {
    'foo': {
      'a': 1
    },
    'bar': {
      'b': 1
    }
  },
  {
    'foo': {
      'a': 1
    },
    'bar': {
      'b': 2
    }
  },
  {
    'foo': {
      'a': 2
    },
    'bar': {
      'b': 1
    }
  },
  {
    'foo': {
      'a': 2
    },
    'bar': {
      'b': 2
    }
  }
>>
```

But if I select directly from an array value that looks like the output I'm expecting the join to give, `SELECT *` isn't eliding the top-level `foo` and `bar` keys:
```
PartiQL> select * from [{'foo':{'a':1},'bar':{'b':1}}]
   | 
===' 
<<
  {
    'foo': {
      'a': 1
    },
    'bar': {
      'b': 1
    }
  }
>>
```

Would anyone be able to help me understand what's going on here? I can't find anywhere in the spec that describes the expected behavior for `SELECT *`, so I assume I'm just missing something, but I haven't yet been able to come up with a coherent explanation for the examples given above!

**Comment by rychipman** [comment]
Some offline discussion with colleagues turned up one possible explanation: `SELECT *` handles binding tuples differently from tuple values.

Specifically, `*` would expand to `TUPLEUNION(key.* for key in b_tup)` if the input is a collection of binding tuples `b_tup`, and simply to `v` if the input is any PartiQL value `v`. 

This is all still speculation on my part though -- any help building my mental model of how `SELECT *` works would be much appreciated!

**Comment by dlurton** [comment]
The intent of the PartiQL specification is to describe how PartiQL extends SQL-92 `SELECT`-`FROM`-`WHERE` queries.  Therefore, if it's not explicitly stated in the PartiQL spec, we should refer to the SQL-92 spec.  That's the intent anyway.

Section 5.3 of the specification as I understand it applies to the logic applied to binding lookups from within the context of the `SELECT` projection, not to the behaviour of `SELECT *`.  

PartiQL's `SELECT *` is a SQL-92 compatibility feature that projects all of the fields of the current set of bindings coming out of the `FROM` clause.

In your example:

```
select * from [{'a':1},{'a':2}] foo cross join [{'b':1},{'b':2}] bar
```

This would be equivalent to the use of the (currently unimplemented) operator `UNION`:

```
select (foo UNION bar) from [{'a':1},{'a':2}] foo cross join [{'b':1},{'b':2}] bar`
```

Hopefully, that makes sense.

For the last provided example, `select * from [{'foo':{'a':1},'bar':{'b':1}}]`, the `FROM` clause is looping over a list with a single struct.  `foo` and `bar` in this case do not even become variable bindings (but one is synthesized because the `FROM` source expression does not mention an `AS` alias.

**Comment by rychipman** [comment]
Thanks for the response @dlurton!

> For the last provided example ... `foo` and `bar` in this case do not even become variable bindings 

This makes sense -- I was confused before re: what the environment was when selecting from a literal array, but I see now that it just creates an anonymous binding.

> In your example:
> ```
> select * from [{'a':1},{'a':2}] foo cross join [{'b':1},{'b':2}] bar
> ```
> 
> This would be equivalent to the use of the (currently unimplemented) operator UNION:
> ```
> select (foo UNION bar) from [{'a':1},{'a':2}] foo cross join [{'b':1},{'b':2}] bar
> ```

Is the `(foo UNION bar)` you describe here the same as `TUPLEUNION(foo, bar)` (for the definition of `TUPLEUNION` given in section 6.3.2 of the spec)? If so, then I think this makes sense!
