### ISSUE TITLE
Assign error code to divide by zero errors

### ISSUE THREAD

**Issue by raganhan** [partiql/partiql-lang-kotlin#28]
We do not currently assign an error code for divide by zero errors.  These tests in our test suite will not pass otherwise.  

```

for::{
    template: [ test::{ name: "divide by zero", sql: $sql, expected: $result } ],
    variableSets: [
        {
            sql: "1 / 0",
            result: error::{
                code: EVALUATOR_DIVIDE_BY_ZERO,  
                properties: {
                    LINE_NUMBER:1,
                    COLUMN_NUMBER:3
                }
            }
        },

        {
            sql: "1 % 0",
            result: error::{
                code: EVALUATOR_DIVIDE_BY_ZERO,
                properties: {
                    LINE_NUMBER:1,
                    COLUMN_NUMBER:3
                }
            }
        },

    ]
}
```

*Migrated from IONSQL-276.*

**Comment by dlurton** [comment]
This doesn't make much sense anymore since error codes have been removed from the test suite.  Additionally, the test suite already has divide and modulo-by-zero tests:

https://github.com/partiql/partiql-lang-kotlin/blob/65a8a495b389c9d4925cdc2db8595f5bcacdb628/testscript/pts/test-scripts/primitive-types/int.sqlts#L161-L167
